services:
 services:
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "anwuat.chai@northbkk.ac.th"
      PGADMIN_DEFAULT_PASSWORD: "1234"
    ports:
      - "8080:80"
